added encryption part
paysense/apollo-utilities pull request #1
Opened 2020-09-14 06:01 UTC by ashwinagalcha-ps

2020-09-16 13:46 UTC, AlMaior requested changes

2020-09-16 13:46 UTC, AlMaior commented on src/main/scala/obfuscation/Encryption.scala
> +	def hashPassword(password: Array[Char],
Add private

2020-09-16 13:46 UTC, AlMaior commented on src/main/scala/obfuscation/Encryption.scala
> +	def prepareKey(password: String): SecretKeySpec = new SecretKeySpec(hashPassword(password.toCharArray, KeySalt), AES)
Make it private

2020-09-16 13:46 UTC, AlMaior commented on src/main/scala/obfuscation/Encryption.scala
> +	def encryptData(key: String, input: Any): String = {
What about S3 solution which we talked about?

2020-09-17 07:00 UTC, ashwinagalcha-ps commented on src/main/scala/obfuscation/Encryption.scala
> +	def encryptData(key: String, input: Any): String = {
I think we should keep this flexible in terms of how users want to pass key. When we are encrypting/ decrypting one should read from S3 & pass key with required permissions.

2020-09-17 10:06 UTC, AlMaior approved these changes

2020-09-17 11:58 UTC, merged